version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: lawgpt-backend
    ports:
      - "8800:8800"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - API_HOST=0.0.0.0
      - API_PORT=8800
    volumes:
      - ./books:/app/books
      - ./db_data:/app/db
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: lawgpt-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
    driver: local
